
export const HELP = 'HELP';
export const DISMISS_HELP = 'DISMISS_HELP';

export const USER_GUESSED_NUMBER = 'USER_GUESSED_NUMBER';
export const NEW_GAME = 'NEW_GAME';

export const FETCH_DESCRIPTION_SUCCESS = 'FETCH_DESCRIPTION_SUCCESS';
export const FETCH_DESCRIPTION_ERROR = 'FETCH_DESCRIPTION_ERROR';
