
export const HELP = 'HELP';
export const DISMISS_HELP = 'DISMISS_HELP';

export const USER_GUESSED_NUMBER = 'USER_GUESSED_NUMBER';
export const NEW_GAME = 'NEW_GAME';

export const FETCH_SCORE_SUCCESS = 'FETCH_SCORE_SUCCESS';
export const FETCH_SCORE_ERROR = 'FETCH_SCORE_ERROR';
